# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_with_ruby_package.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service_with_ruby_package.proto", :syntax => :proto3) do
    add_message "example.hello_world.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "example.hello_world.HelloResponse" do
      optional :message, :string, 1
    end
  end
end

module testpackage
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.hello_world.HelloRequest").msgclass
  HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("example.hello_world.HelloResponse").msgclass
end
