# Code generated by protoc-gen-twirp_ruby 1.3.0, DO NOT EDIT.
require 'twirp'
require_relative 'service_with_ruby_package_pb.rb'

module testpackage
  class HelloWorldService < Twirp::Service
    package 'example.hello_world'
    service 'HelloWorld'
    rpc :Hello, HelloRequest, HelloResponse, :ruby_method => :hello
  end

  class HelloWorldClient < Twirp::Client
    client_for HelloWorldService
  end
end
